### ISSUE TITLE
Connection error received. 

### ISSUE THREAD

**Issue by baibhavkumarpoudel** [baibhavkumarpoudel/project3-frontend#3] opened 2021-06-17 16:01 UTC
1. We tried to connect our backend to frontend,  but we have been receiving cannot GET/ error. I know the issue is with the backend after looking up articles on stackoverflow, but even w/ everything we have been trying, the localhost still gives us the error below. 
2.  articles we looked at:
 - https://stackoverflow.com/questions/38906961/node-express-cannot-get-route/38907078
 - https://www.a2hosting.com/kb/cpanel/cpanel-software/node-js-application-error-message-cannot-get-url
 
  (the image below is the outcome of the browser when both npm start and node server.js are running)

![image](https://user-images.githubusercontent.com/82845499/122432262-ca1f7e80-cf5a-11eb-8809-64fe9be3bed1.png)

**Comment by Skyvassa** [comment] 2021-06-17 16:03
In addition, when I attempt to run run this on my end I also run into a similar but different issue. One potential solution we may have noted is installing cors, but have concerns once again about severely damaging our code and being unable to open a backup. as noted with this url.
https://stackoverflow.com/questions/45115309/error-options-neterr-connection-refused/45247822
![image](https://user-images.githubusercontent.com/82845166/122433041-d825cd00-cf63-11eb-9a37-04a60f9e3429.png)

**Comment by CRHarding** [comment] 2021-06-17 16:04
In your express app I don't see any route set up for just '/', hence the `Cannot GET '/'`.

**Comment by CRHarding** [comment] 2021-06-17 16:05
What might be the issue is what port is your react app running at? 3000 or 3001?

**Comment by CRHarding** [comment] 2021-06-17 16:05
In your backend code it says your express app is running on port 3000, so I'd bet that your react app is running at 3001, try going to `localhost:3001` and see if that fixes that issue.

**Comment by CRHarding** [comment] 2021-06-17 16:07
For yours @Skyvassa try in your signup.js file using `https` instead of just `http`, sometimes that solves the cors errors.

**Comment by Skyvassa** [comment] 2021-06-17 16:09
> For yours @Skyvassa try in your signup.js file using `https` instead of just `http`, sometimes that solves the cors errors.

I have not yet installed cors. Is that something that is needed for backend+frontend communication? After our conversation yesterday we've been nervous to touch code that we're not familiar with.

Also, Our backend is running app.listen(3000....... etc). Our axios.posts in the frontend are running on localhost:3001. When we try to run localhost:3001 we get no response.

**Comment by CRHarding** [comment] 2021-06-17 16:10
When you run your react server what port does it say it's running at

**Comment by Skyvassa** [comment] 2021-06-17 16:11
When we npm start it opens to localhost3000

**Comment by CRHarding** [comment] 2021-06-17 16:12
That means your express app isn't running, you can't have both your express app and your react app running on the same port. So stop your react server and start your express server and then restart your react server.

**Comment by baibhavkumarpoudel** [comment] 2021-06-17 16:17
We reset the react app while the express server was running. When prompted for a different port, we said yes and it automatically went to 3001. The rendering worked, but when trying to use "signup", it gives us the error below. 

![image](https://user-images.githubusercontent.com/82845499/122434926-25eb0700-cf5d-11eb-8ac5-afb62177a6cc.png)

![image](https://user-images.githubusercontent.com/82845499/122435094-4e730100-cf5d-11eb-9a47-8fe5d5a9c016.png)

**Comment by CRHarding** [comment] 2021-06-17 16:18
You're trying to post from your React app, right? And your react app is running on port 3001, but you're sending your request to `http://localhost:3001/auth/signup` when your express app is running at `http://localhost:3000`, try changing the port number in your React application to match the port that your express app is running on.

**Comment by Skyvassa** [comment] 2021-06-17 16:25
Our react app is only running on 3001 because when we start the express app first on listen:3000, we get the error "Something is already running on port 3000". We adjusted all of our axios.gets to (localhost:3000) to try and match the express app, but when prompted again for "Something is already running...would you like to run on another port" and it tries to start react on 3001, it just spins. It does not render.

**Comment by Skyvassa** [comment] 2021-06-17 16:25
We could not locate a default react app port designator.

**Comment by CRHarding** [comment] 2021-06-17 16:31
That's not what the issue is, what I said was that since your react app is running on port 3001, and your express app is running on port 3000, you need to send axios requests from your react app TO port 3000, in your code right now you're going to port 3001 (based on the error).

When you say the react app just spins and doesn't render, what url are you going to? Because if you're going to `localhost:3001` you should be seeing the Home component, and if not make sure to check that there aren't any errors being thrown in your console.

**Comment by baibhavkumarpoudel** [comment] 2021-06-17 16:36
yep, we tried changing the axios.get routes inside the react app to 3000 (same port as node server.js), and the url is mentioning we're at localhost:3001 when we npm start (because node server.js is running on 3000). But there is no error given to us on our console, just a loading browser with url: localhost/3001

**Comment by CRHarding** [comment] 2021-06-17 16:36
Shouldn't the url be localhost:3001?

**Comment by baibhavkumarpoudel** [comment] 2021-06-17 16:37
yes it is. that is what the react app is running on. 
![image](https://user-images.githubusercontent.com/82845499/122438562-744dd500-cf60-11eb-9099-3441d527c9ac.png)

**Comment by CRHarding** [comment] 2021-06-17 16:41
Alright, I'm cloning them down and will let you know what I find out.

**Comment by baibhavkumarpoudel** [comment] 2021-06-17 16:42
ok thank you. we appreciate it

**Comment by CRHarding** [comment] 2021-06-17 16:46
I cloned your front end, ran npm install, cloned your backend, ran npm install, changed the port in your express app to listen on port 3001, ran both servers, and it's loading.

**Comment by CRHarding** [comment] 2021-06-17 16:46
![Screen Shot 2021-06-17 at 12 46 28 PM](https://user-images.githubusercontent.com/34920615/122439882-09a19700-cf6a-11eb-95e0-b1573a8163ba.png)

**Comment by CRHarding** [comment] 2021-06-17 16:47
Not sure what you all were running into but try changing express to listen to port 3001 instead and restart your servers.

**Comment by Skyvassa** [comment] 2021-06-17 16:55
We set our express app to Listen to port 3001, and have our react axios.get on 3000. When we start the express app first, then npm start the react app, it does render the page sucessfully again. 

However, once we try to run our Signup Submit as we had in the earlier photo attached again here, we are still getting the error "Post localhost:3000/auth/signup" 404 (Not Found). I suppose this may be a different error, we can do some review and see what workarounds we have.
https://user-images.githubusercontent.com/82845499/122434926-25eb0700-cf5d-11eb-8ac5-afb62177a6cc.png

**Comment by CRHarding** [comment] 2021-06-17 16:58
You're now going to have to switch your axios requests to go to `localhost:3001` because that's where your express app is listening.

**Comment by baibhavkumarpoudel** [comment] 2021-06-17 17:08
thank you for that clearance. But it brought us to a completely different error which Skyler touched base with earlier on this issue ticket regarding cors. Skyler will include a source he was looking into for the issue below. 

![image](https://user-images.githubusercontent.com/82845499/122442519-47032600-cf64-11eb-8d3f-5d9ebef4a4c6.png)

is cors required for frontend and backend to communicate ?

Skyler:
https://stackoverflow.com/questions/46522749/how-to-solve-redirect-has-been-blocked-by-cors-policy-no-access-control-allow

**Comment by Skyvassa** [comment] 2021-06-17 17:08
https://stackoverflow.com/questions/46522749/how-to-solve-redirect-has-been-blocked-by-cors-policy-no-access-control-allow

**Comment by Skyvassa** [comment] 2021-06-17 17:13
Followup: We made that https adjustment like mentioned earlier, another small error but that scary looking Access error went away. Must have been a url issue.

**Comment by Skyvassa** [comment] 2021-06-17 17:17
Just in case you're reviewing, we're taking lunch now to be back before we start group review.

**Comment by CRHarding** [comment] 2021-06-17 18:00
Do you mind closing this issue ticket and making a new one, since the cors error / routing errors are gone I'm not sure what else is going on right now.

**Closed as completed** 2021-06-17 18:27 UTC
